# Generated by Django 2.0.7 on 2018-09-09 08:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LookupRajon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rajons', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': ('Районы',),
                'verbose_name_plural': 'Районы',
                'db_table': 'lookup_rajon',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LookupRegion',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('regions', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': ('Регионы',),
                'verbose_name_plural': 'Регионы',
                'db_table': 'lookup_region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_medical_examination', models.DateField(blank=True, null=True)),
                ('purpose_medical_examination', models.CharField(blank=True, choices=[('Огляд водія', 'Огляд водія'), ('Дозвіл на зброю', 'Дозвіл на зброю'), ('Санітарна книжка', 'Санітарна книжка'), ('Сертифікат нарколога', 'Сертифікат нарколога'), ('Сертифікат психіатора', 'Сертифікат психіатора'), ('Довідка в бесейн', 'Довідка в бесейн'), ('Форма 086', 'Форма 086'), ('Інші', 'Інші')], default='Огляд водія', help_text='Введите цель медосмотра', max_length=20, verbose_name='Цель')),
                ('dat_end', models.DateField(blank=True, null=True)),
                ('date_update', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': ('Медосмотры',),
                'verbose_name_plural': 'Медосмотры',
                'db_table': 'medexamination',
                'ordering': ['date_medical_examination'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='first_name', max_length=100, verbose_name='Фамилия')),
                ('last_name', models.CharField(db_column='last_name', max_length=100, verbose_name='Имя')),
                ('patron_name', models.CharField(max_length=150, verbose_name='Отчество')),
                ('inn', models.CharField(max_length=10, verbose_name='ИНН')),
                ('date_birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('phone_home', models.CharField(max_length=10, verbose_name='Домашний телефон')),
                ('phone_mobile', models.CharField(max_length=13, verbose_name='Мобильный телефон')),
                ('email', models.CharField(max_length=250)),
                ('place_of_work', models.TextField(blank=True, db_column='place_of_work', null=True, verbose_name='Место работы')),
                ('reference_number', models.CharField(max_length=30)),
                ('addr_locality', models.CharField(blank=True, choices=[('м', 'місто'), ('с', 'село'), ('смт', 'селище міського типу')], default='с', help_text='Введите тип населенного пункта', max_length=3, verbose_name='Тип населенного пункта')),
                ('addr_city', models.CharField(max_length=100)),
                ('addr_abbreavation', models.CharField(blank=True, choices=[('бульвар', 'бульвар'), ('вул', 'вулиця'), ('кв', 'квартал'), ('пр-к', 'провулок'), ('пр', 'проспект'), ('тупік', 'тупік'), ('узвіз', 'узвіз'), ('шосе', 'шосе')], default='вул', help_text='Введите абривиатуру улицы', max_length=10)),
                ('addr_street', models.CharField(max_length=200)),
                ('addr_house', models.CharField(max_length=5)),
                ('addr_corpus', models.CharField(max_length=5)),
                ('addr_room', models.CharField(max_length=5)),
                ('addr_index', models.CharField(max_length=5)),
                ('date_update', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('rajon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_card.LookupRajon')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_card.LookupRegion')),
            ],
            options={
                'verbose_name': ('Пациент',),
                'verbose_name_plural': 'Пациент',
                'db_table': 'patient',
                'ordering': ['first_name'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='medexamination',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_card.Patient'),
        ),
        migrations.AddField(
            model_name='lookuprajon',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_card.LookupRegion'),
        ),
    ]
