# Generated by Django 2.0.7 on 2018-09-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_card', '0002_auto_20180909_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.CharField(error_messages={'required': 'Please provide your email address.', 'unique': 'An account with this email exist.'}, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='inn',
            field=models.CharField(error_messages={'required': 'Please provide your inn.', 'unique': 'An account with this inn exist.'}, max_length=10, unique=True, verbose_name='ИНН'),
        ),
    ]
