# Generated by Django 2.0.7 on 2018-09-11 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_card', '0003_auto_20180910_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='addr_abbreavation',
            field=models.CharField(blank=True, choices=[('бульвар', 'бульвар'), ('вул', 'вулиця'), ('кв', 'квартал'), ('пр-к', 'провулок'), ('пр', 'проспект'), ('тупік', 'тупік'), ('узвіз', 'узвіз'), ('шосе', 'шосе')], default='вул', help_text='Введите абривиатуру улицы', max_length=10, verbose_name='Тип(улица, бульвар...)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='addr_corpus',
            field=models.CharField(default=0, max_length=5, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='addr_house',
            field=models.CharField(max_length=5, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='addr_index',
            field=models.CharField(max_length=5, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='addr_room',
            field=models.CharField(default=0, max_length=5, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='addr_street',
            field=models.CharField(max_length=200, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_update',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.CharField(error_messages={'required': 'Please provide your email address.', 'unique': 'An account with this email exist.'}, max_length=250, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rajon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_card.LookupRajon', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='reference_number',
            field=models.CharField(max_length=30, verbose_name='Номер л-го удостверения'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_card.LookupRegion', verbose_name='Область'),
        ),
    ]
