# Generated by Django 2.0.7 on 2018-09-11 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_card', '0006_auto_20180911_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medexamination',
            name='date_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
