# Generated by Django 2.0.7 on 2018-09-13 13:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_card', '0007_auto_20180911_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medexamination',
            name='dat_end',
            field=models.DateField(default=datetime.datetime(2020, 9, 13, 16, 13, 47, 198069), verbose_name='Дата действия справки'),
        ),
        migrations.AlterField(
            model_name='medexamination',
            name='date_medical_examination',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Дата медосмотра'),
        ),
        migrations.AlterField(
            model_name='medexamination',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_patient', to='app_card.Patient'),
        ),
    ]
