# Generated by Django 2.0.7 on 2018-09-15 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_card', '0008_auto_20180913_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medexamination',
            name='dat_end',
            field=models.DateField(default=datetime.datetime(2020, 9, 15, 14, 36, 10, 678539), verbose_name='Дата действия справки'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='addr_city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='reference_number',
            field=models.CharField(max_length=30, null=True, verbose_name='Номер л-го удостверения'),
        ),
    ]
