# Generated by Django 2.1.1 on 2018-09-25 09:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_card', '0009_auto_20180915_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medexamination',
            options={'managed': True, 'ordering': ['-id'], 'verbose_name': ('Медосмотры',), 'verbose_name_plural': 'Медосмотры'},
        ),
        migrations.AddField(
            model_name='medexamination',
            name='patient_status',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', help_text='Введите статус уведомления', max_length=3, verbose_name='Статус уведомления'),
        ),
        migrations.AlterField(
            model_name='medexamination',
            name='dat_end',
            field=models.DateField(default=datetime.datetime(2020, 9, 25, 12, 32, 57, 266327), verbose_name='Дата действия справки'),
        ),
        migrations.AlterField(
            model_name='medexamination',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_card.Patient'),
        ),
    ]
