# Generated by Django 2.0.7 on 2018-11-22 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_card', '0011_auto_20181122_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medexamination',
            name='dat_end',
            field=models.DateField(default=datetime.datetime(2020, 11, 22, 21, 54, 44, 820095), verbose_name='Дата действия справки'),
        ),
        migrations.AlterField(
            model_name='medexamination',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
